### ISSUE TITLE
scheiß Brandl 

### ISSUE THREAD

**Issue by GideonUng** [Greyhash-dev/netra#1]
Hahaha jup. 
LG war auch beim kepler und seit 6 Jahren in der games Industrie.

**Comment by Greyhash-dev** [comment]
Nice xD
Ich finde es echt schade, man könnte was sinnvolles in IT lernen, aber nein, wir machen irgendeinen scheiß der wirklich niemandem was bringt und wenn man einen Vorschlag bringt, wird man nur kritisiert oder ignoriert dafür...
